# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jira < Formula
  desc "Interactive command-line tool for Jira"
  homepage "https://github.com/iatsiuk/jira-cli"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iatsiuk/jira-cli/releases/download/v1.8.0/jira_1.8.0_macOS_x86_64.tar.gz"
      sha256 "8b98b92a4382ec0205b43faa2f33e6117bab6778dea176e86262e9019c12f8e9"

      define_method(:install) do
        bin.install "bin/jira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iatsiuk/jira-cli/releases/download/v1.8.0/jira_1.8.0_macOS_arm64.tar.gz"
      sha256 "bc556a0168179a5657d5c008fdb8a862dd9acfca9c35fb8117ce4bdebcc2ce71"

      define_method(:install) do
        bin.install "bin/jira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iatsiuk/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_x86_64.tar.gz"
      sha256 "e474f1df3b7dd741fce16a8a9ec47017abf3dd1a1c4c11491e7e78f6cb172425"
      define_method(:install) do
        bin.install "bin/jira"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/iatsiuk/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_armv6.tar.gz"
      sha256 "41005670696f63db924f4e14fb077b4ab78c47a82cc7d0e519453d27d5515c57"
      define_method(:install) do
        bin.install "bin/jira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iatsiuk/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_arm64.tar.gz"
      sha256 "0bc3524c621ab248238d025d1b35871c526cd6a050a37354eabeec1d5e1b8e84"
      define_method(:install) do
        bin.install "bin/jira"
      end
    end
  end
end
