# This file was generated by GoReleaser. DO NOT EDIT.
cask "datadog-cli" do
  version "0.7.1"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "4d8098863275efc26e669011cbc63a8724e2b72b6c673604d74aaa4f25596858"
    end
    on_arm do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "4f2e0752d7e1202a24e8d1f38ae9fb96cc24e21f1524a43234e52819b40b044d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_linux_amd64.tar.gz"
      sha256 "9449c7cbce38f50d705f53f219af3952ad9590010af123f386c92e9dc834dc7b"
    end
    on_arm do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_linux_arm64.tar.gz"
      sha256 "9d78c71b3838e0321ed79bed4cbad593c010a4c87b8e7061ad34c17d118cfa72"
    end
  end

  name "datadog-cli"
  desc "CLI tool for Datadog - query logs, traces, and events from the terminal"
  homepage "https://github.com/iatsiuk/datadog-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datadog-cli"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/datadog-cli' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the datadog-cli binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/datadog-cli
  EOS
end
