# This file was generated by GoReleaser. DO NOT EDIT.
cask "datadog-cli" do
  name "datadog-cli"
  desc "CLI tool for Datadog - query logs, traces, and events from the terminal"
  homepage "https://github.com/iatsiuk/datadog-cli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datadog-cli"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "55ea20412e56d6321f79bc19046798406ad6b36b70dd8bde3bfd1622e4abdc69"
    end
    on_arm do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "fd08296a8cc525f308600deba2cc4ed4d0cf3a7ac31260b805705b4e6c69711d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_linux_amd64.tar.gz"
      sha256 "5326a1dae5a3dc969adafe6f75460f0050734b81c4f5e5018e5edd3db1832549"
    end
    on_arm do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_linux_arm64.tar.gz"
      sha256 "ead70094ebd790efd86a66c5e1746a3dbf6aed9aef98c4b6a754e553c16acc4a"
    end
  end

  # No zap stanza required
end
