# This file was generated by GoReleaser. DO NOT EDIT.
cask "datadog-cli" do
  name "datadog-cli"
  desc "CLI tool for Datadog - query logs, traces, and events from the terminal"
  homepage "https://github.com/iatsiuk/datadog-cli"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datadog-cli"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "22e5bfd623ea46fb9b0e7d9c9dd00c5f10edd65859df8ae63d29cc9ae478dae2"
    end
    on_arm do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "01e302ac404722f29a58d28e785b886d0002e2590bee0a68a7689198855a9592"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_linux_amd64.tar.gz"
      sha256 "f8097a7702954de5508008a02f106b1a0e4ac6e0b38242cec043cc62f1fb96ae"
    end
    on_arm do
      url "https://github.com/iatsiuk/datadog-cli/releases/download/v#{version}/datadog-cli_#{version}_linux_arm64.tar.gz"
      sha256 "d6e9e6061c3d1df746d2ee152ad5a490ac3d6c123b4cc2c031450ef868c793b8"
    end
  end

  # No zap stanza required
end
