# This file was generated by GoReleaser. DO NOT EDIT.
cask "firefox-ctl" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "00f959df9009ce5748c0fd560112fef96290a457bab2c7ddef26ae44ac19cd14"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b4a88084498dad9cf06654a58c1b85e96e776efd6b734d941bb2144a03b815f"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "38fa91741fb2f9293604a48a1a92f765808ee73d589a0ec960692429636a5b1d"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "firefox-ctl"
  desc "Control Firefox from the terminal: tabs, DOM, screenshots and DevTools over native messaging"
  homepage "https://github.com/iatsiuk/firefox-ctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firefox-ctl"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/firefox-ctl' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the firefox-ctl binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    Register the native messaging host with Firefox once:
      firefox-ctl install

    To uninstall:
      firefox-ctl install --uninstall
      brew uninstall --cask iatsiuk/tap/firefox-ctl
  EOS
end
