# This file was generated by GoReleaser. DO NOT EDIT.
cask "firefox-ctl" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "d0b44b07a2712121425928f12021625e56bbd4299ceea5361074c45cc338bc5f"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "558dc8f544ea84a21ea27c7466f7f6b5b2e8df9cb05f7f318183702d6dd96ae6"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0bcad3e3242829d0973448eebb90541168fb864a541e56dd77aa7170c4654d64"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "firefox-ctl"
  desc "Control Firefox from the terminal: tabs, DOM, screenshots and DevTools over native messaging"
  homepage "https://github.com/iatsiuk/firefox-ctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firefox-ctl"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/firefox-ctl' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the firefox-ctl binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    Register the native messaging host with Firefox once:
      firefox-ctl install

    To uninstall:
      firefox-ctl install --uninstall
      brew uninstall --cask iatsiuk/tap/firefox-ctl
  EOS
end
