# This file was generated by GoReleaser. DO NOT EDIT.
cask "firefox-ctl" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "9b67a90ba2b2747a32dc4255629bcdea19c262a79ae3fa3286a9a6d12e5e0c56"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d5fb05367d3cd344a0ed19861239441feadcdaf8af5106e44fd23aa410039554"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "45387b81c2a34a864a5343fa02b52951347298ed461318d9febb2e69823578ef"
      url "https://github.com/iatsiuk/firefox-ctl/releases/download/v#{version}/firefox-ctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "firefox-ctl"
  desc "Control Firefox from the terminal: tabs, DOM, screenshots and DevTools over native messaging"
  homepage "https://github.com/iatsiuk/firefox-ctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firefox-ctl"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/firefox-ctl' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the firefox-ctl binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    Register the native messaging host with Firefox once:
      firefox-ctl install

    To uninstall:
      firefox-ctl install --uninstall
      brew uninstall --cask iatsiuk/tap/firefox-ctl
  EOS
end
