# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira" do
  name "jira"
  desc "Interactive command-line tool for Jira"
  homepage "https://github.com/iatsiuk/jira-cli"
  version "1.7.0-ad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_darwin_amd64.tar.gz"
      sha256 "b34d2491ee0450960e4747ee06aeb5f424f593f37fe25056591537bae51b8a30"
    end
    on_arm do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_darwin_arm64.tar.gz"
      sha256 "779896f76bd110d2f06841dcfd117a000b1a31a220cdc44edbd1b955b5aef706"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_linux_amd64.tar.gz"
      sha256 "a76a52c510e2067e80c952bb98445a23788c7b408ad85f52f55102c1b515a3c9"
    end
    on_arm do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_linux_arm64.tar.gz"
      sha256 "711e6ea39bd782b0ce4815d62e3cd5e5da33fc9be049260142aec632d1b3aa46"
    end
  end

  # No zap stanza required
end
