# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira" do
  name "jira"
  desc "Interactive command-line tool for Jira"
  homepage "https://github.com/iatsiuk/jira-cli"
  version "1.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_darwin_amd64.tar.gz"
      sha256 "d0a713103ddf1b1f55b4bdc29c79433ef53ba30fc6e16fe138618bcee3fb1f75"
    end
    on_arm do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_darwin_arm64.tar.gz"
      sha256 "fc12224fa51bec2535251b69d8c2017905eadc4567a48d71cd1529062eef8416"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_linux_amd64.tar.gz"
      sha256 "29c2a70591c2c0e503b2f47814368738144b51b83658ec0f29598ba4d49a5ae8"
    end
    on_arm do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_linux_arm64.tar.gz"
      sha256 "d67f11b5b0565c8d6009b115ad7b76e607fb13ff327b3782b0d014670a496d0c"
    end
  end

  # No zap stanza required
end
