# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira" do
  name "jira"
  desc "Interactive command-line tool for Jira"
  homepage "https://github.com/iatsiuk/jira-cli"
  version "1.7.0-ad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_darwin_amd64.tar.gz"
      sha256 "000a585c307639ac7b09ac7dd9b0af39993009a9d5058c5ab08cf1f4465c870d"
    end
    on_arm do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_darwin_arm64.tar.gz"
      sha256 "39ffc3bde592c7df4c23aa09e392996a6768174b8f3ec52e96ded115ba41fda2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_linux_amd64.tar.gz"
      sha256 "ad955e9cd09fdaef2ad0efe5baeb0c274bd62ecd50955a3fcbae96abba140429"
    end
    on_arm do
      url "https://github.com/iatsiuk/jira-cli/releases/download/v#{version}/jira_#{version}_linux_arm64.tar.gz"
      sha256 "397de995902c1b5ca0def0725448f02a4f77e240c728f80721c249c96653edf9"
    end
  end

  # No zap stanza required
end
