# This file was generated by GoReleaser. DO NOT EDIT.
cask "linear-cli" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "cff09b5b7893b98948b199b117d800b6cf85b256019eb0423704203b03993438"
    end
    on_arm do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "1a9ea281fe2a38cbcabed43b80581fa0c765901c3d0e41f56e7a03deb9c6ea9e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_linux_amd64.tar.gz"
      sha256 "86f4234698a4fbe5d5a43a422f38897e0a1cc4817ab6023150e3cdb4ae820144"
    end
    on_arm do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_linux_arm64.tar.gz"
      sha256 "2a7db5f42a6dc4852ce1aae025605a2f54b4a0686ba370ecd8ade4ef9d93decb"
    end
  end

  name "linear-cli"
  desc "CLI tool for Linear - manage issues, projects, and teams from the terminal"
  homepage "https://github.com/iatsiuk/linear-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linear-cli"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/linear-cli' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the linear-cli binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/linear-cli
  EOS
end
