# This file was generated by GoReleaser. DO NOT EDIT.
cask "linear-cli" do
  name "linear-cli"
  desc "CLI tool for Linear - manage issues, projects, and teams from the terminal"
  homepage "https://github.com/iatsiuk/linear-cli"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linear-cli"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "9a9bf426b3690cf6b128f686af06b66b089b47be081655c5cb5792d53dc9dfcb"
    end
    on_arm do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "bfa39b20c0798faa2b68b35989ac9fc63a9660aff0e015d61ff11cd8607a550f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_linux_amd64.tar.gz"
      sha256 "b6c89a43b6fc824275e57e292e4ceaf880d323fcbed3607e7b5f6c3ba02b2543"
    end
    on_arm do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_linux_arm64.tar.gz"
      sha256 "128bb6b1584a675df5883f109cc280cc5335c91fe71012d5319768572ec8f8e6"
    end
  end

  # No zap stanza required
end
