# This file was generated by GoReleaser. DO NOT EDIT.
cask "linear-cli" do
  name "linear-cli"
  desc "CLI tool for Linear - manage issues, projects, and teams from the terminal"
  homepage "https://github.com/iatsiuk/linear-cli"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linear-cli"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "3c785fcc12dd7b20670057b07a015b40cf9de5ab24cb86d6bbaca5b3b73997bc"
    end
    on_arm do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "5d0dfc9e888bae7312623a0e278e9447f30d9c412a34a98fc84f136600ccc966"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_linux_amd64.tar.gz"
      sha256 "1c66a27f790d47db09ca958634e602e73a5a3efa7b032ebbe1c3b2c450a9e370"
    end
    on_arm do
      url "https://github.com/iatsiuk/linear-cli/releases/download/v#{version}/linear-cli_#{version}_linux_arm64.tar.gz"
      sha256 "c20c4d243e34705dc09e2491e09ceab2212414b5f22b8c06aac3d3e5ecf3c4a6"
    end
  end

  # No zap stanza required
end
