# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  name "notion-cli"
  desc "CLI tool for Notion - query, manage, and interact with Notion workspaces"
  homepage "https://github.com/iatsiuk/notion-cli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "bda9b22494fbe58a6e61891990e8a1a3308d37c5f3f005162132e14086a9a673"
    end
    on_arm do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "1bc04d15ddb100148a3f3c32a8e46fc9857a4ef2019b8ca5d082de325a1a7054"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_linux_amd64.tar.gz"
      sha256 "ad9b312c77cbf4d631941f7f59ab8357e284639b500379bb54f7e544bb8c1236"
    end
    on_arm do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_linux_arm64.tar.gz"
      sha256 "c07039fbe62e35494945afc322b949de184519fd947933131d510e98761b973b"
    end
  end

  # No zap stanza required
end
