# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "bcc5ed1a16d7ee1653946466fb972d51ed03d7bc3776e5b4b318c1d143a159a0"
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bc0dca72be7bb993b73d06955a6c5ef1e7520563bc41eaee6da66a3ace0260a"
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "73e00ea75efe4e0b6dfe218a8419f50f42cc3705f5bfdfb8d0c22bf1c6734fd7"
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6244eff7a80067a43ffa8bb7909d2c14c32fc07b4ff1da9d278b49e8f325350d"
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "notion-cli"
  desc "CLI tool for Notion - query, manage, and interact with Notion workspaces"
  homepage "https://github.com/iatsiuk/notion-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/notion-cli' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the notion-cli binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/notion-cli
  EOS
end
