# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  version "0.5.1"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "13feaae12360f284de1e05f3aa0f1bd189a2b30626c1ab95b79c723e944f5ccb"
    end
    on_arm do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "da0cf1c87312e8a238d20ffbea9c950c74ff2079c5aa30db59abfb144a19980d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_linux_amd64.tar.gz"
      sha256 "1c0d9a93d9166f0fb05cd843cf6a75fa114c3991d9b8f0e96c273b7eee4ea1a7"
    end
    on_arm do
      url "https://github.com/iatsiuk/notion-cli/releases/download/v#{version}/notion-cli_#{version}_linux_arm64.tar.gz"
      sha256 "fb5cd852ce79b7653881f5c13846f506bb7fee8f7340e271c8121a2b853bbf1e"
    end
  end

  name "notion-cli"
  desc "CLI tool for Notion - query, manage, and interact with Notion workspaces"
  homepage "https://github.com/iatsiuk/notion-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/notion-cli' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the notion-cli binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/notion-cli
  EOS
end
