# This file was generated by GoReleaser. DO NOT EDIT.
cask "orx" do
  name "orx"
  desc "CLI tool for querying multiple LLMs in parallel via OpenRouter"
  homepage "https://github.com/iatsiuk/orx-cli"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orx"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "4c0b6f63d7eaa480fb8fb91070962881d9310f1176ea6e2ddff4fd779eb1cd6e"
    end
    on_arm do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "fcadb93e15150cbd09c4921215116efc87342dc424c6fdcfc93e911e8a632f35"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_linux_amd64.tar.gz"
      sha256 "d32834acec1551d31eb93da5f432b3059974257a90ab2e789e2994512b611ce8"
    end
    on_arm do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_linux_arm64.tar.gz"
      sha256 "66db4830581ae6af2afbaab79a9c4659e1f0f4d5be366975f728f85c64299744"
    end
  end

  # No zap stanza required
end
