# This file was generated by GoReleaser. DO NOT EDIT.
cask "orx" do
  version "1.6.1"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "f411df116d442c349e367026ed5ac4c5ec65597b30b113b526cefd729ab3f6ec"
    end
    on_arm do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "6ca5def84abe164a41d487b264ad076a3699ac1971d424546d5e98f08dcaf382"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_linux_amd64.tar.gz"
      sha256 "edf2cb9d009730cc1cce42f8a79149bfe3af724427f7329fd01e7f0a6c9b13c5"
    end
    on_arm do
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_linux_arm64.tar.gz"
      sha256 "5d5c622e586cc620c37860672a66ef5b6d3d543ae9d61a7b17f2892916adec0c"
    end
  end

  name "orx"
  desc "CLI tool for querying multiple LLMs in parallel via OpenRouter"
  homepage "https://github.com/iatsiuk/orx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orx"
  binary "orx-ralphex-review"

  # No zap stanza required

end
