# This file was generated by GoReleaser. DO NOT EDIT.
cask "orx" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "9dec5a5197b2735fc4f6091b6bf8137101638db0a7d24e1309cfef6d5a3e70ac"
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f623586bfc466953e7769d1642da356193d5c899afcb3441506c454db60261d6"
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cff25b1c19706286b36e07a3238df564efc1a9647f1294a3a138018456412c79"
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e38deb695c51728581a4372f34b11c668038248253e95961d7201c23642b01f4"
      url "https://github.com/iatsiuk/orx-cli/releases/download/v#{version}/orx-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orx"
  desc "CLI tool for querying multiple LLMs in parallel via OpenRouter"
  homepage "https://github.com/iatsiuk/orx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orx"
  binary "orx-ralphex-review"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/orx' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the orx binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/orx
  EOS
end
