# This file was generated by GoReleaser. DO NOT EDIT.
cask "r-cli" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "5c830e07c82cea9e911a452b5008ac08fc5293554cc9b1ac677c3bb53a188432"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cee139672c1a44b7ffecffc52e917f088d2755818fff69b7f9f1ef91f74d291a"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd1b9a931aea0d4c0c6153283cc0c7886e5b8e09077e49ea203f8d71a9aa324b"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "801946d28fe905bed53ee618d05b809575ecad1156ac532c1e2e9a30093d7c97"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "r-cli"
  desc "CLI tool for RethinkDB - query, manage, and interact with RethinkDB databases"
  homepage "https://github.com/iatsiuk/r-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "r-cli"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/r-cli' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the r-cli binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/r-cli
  EOS
end
