# This file was generated by GoReleaser. DO NOT EDIT.
cask "r-cli" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "4d46748425d27ff44ab1374cf0cef5060b0054b45a11dbda69d226f9f271d888"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "277baf219be0fc79fec9284ed57d83ddd45748970e1a22a32e8df17d31407610"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "128f4ebf493b95da9ee3891af649c39e395d92e49efe2a690ec4b0a3f112ddc5"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "609e8a0cc47e0c6e220dda0751afd7b0fd296eb77a7db11b875c4b3cc409ab1f"
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "r-cli"
  desc "CLI tool for RethinkDB - query, manage, and interact with RethinkDB databases"
  homepage "https://github.com/iatsiuk/r-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "r-cli"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/r-cli' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the r-cli binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/r-cli
  EOS
end
