# This file was generated by GoReleaser. DO NOT EDIT.
cask "r-cli" do
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "14b5fa9decf2e652f198bdf88618d64b4fda604954ac9b00e31f3a8b28d4dee9"
    end
    on_arm do
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "fabb7928140bc8d684189a5b7fe906a745488a8e7bbd32e8df70046022cc49f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_linux_amd64.tar.gz"
      sha256 "cbd6f8d873e86118a0ab446b03409fb8ef6e57cbb9ea9cf39e8bc633083da7d1"
    end
    on_arm do
      url "https://github.com/iatsiuk/r-cli/releases/download/v#{version}/r-cli_#{version}_linux_arm64.tar.gz"
      sha256 "a0b6294d0e451f528ada4c4fed07987c568ab8c3d70c01e2ba60290691818b2b"
    end
  end

  name "r-cli"
  desc "CLI tool for RethinkDB - query, manage, and interact with RethinkDB databases"
  homepage "https://github.com/iatsiuk/r-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "r-cli"

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/r-cli' 2>/dev/null; true"]
  end

  # No zap stanza required

  caveats <<~EOS
    Quarantine attribute (com.apple.quarantine) is automatically removed
    from the r-cli binary during installation to prevent Gatekeeper warnings.
    See: https://github.com/Homebrew/brew/issues/20755

    To uninstall:
      brew uninstall --cask iatsiuk/tap/r-cli
  EOS
end
